### ISSUE TITLE
hydrogen ssr error when using pnpm

### ISSUE THREAD

**Issue by bennobuilder** [physical-art/physicaldotart#1]
Hydrogen doesn't seem to work properly with `pnpm` so I've to switch to `yarn` again :/

```
C:\Users\benno\Desktop\Workspace\Projects\_web\physicaldotart\apps\landing>pnpm dev

> landing@0.0.0 dev C:\Users\benno\Desktop\Workspace\Projects\_web\physicaldotart\apps\landing
> shopify hydrogen dev

  > Local: http://localhost:3000/
  > Network: use `--host` to expose

Failed to resolve force included dependency: react-helmet-async
3:40:46 PM [vite] Error when evaluating SSR module /@fs/C:/Users/benno/Desktop/Workspace/Projects/_web/physicaldotart/node_modules/.pnpm/prop-types@15.8.1/node_modules/prop-types/index.js?v=e3bc4c16:
ReferenceError: require is not defined
    at /@fs/C:/Users/benno/Desktop/Workspace/Projects/_web/physicaldotart/node_modules/.pnpm/prop-types@15.8.1/node_modules/prop-types/index.js?v=e3bc4c16:9:17
    at instantiateModule (C:\Users\benno\Desktop\Workspace\Projects\_web\physicaldotart\node_modules\.pnpm\vite@2.9.14\node_modules\vite\dist\node\chunks\dep-c9998dc6.js:50311:15)
3:40:46 PM [vite] Error when evaluating SSR module /@fs/C:/Users/benno/Desktop/Workspace/Projects/_web/physicaldotart/node_modules/.pnpm/react-helmet-async@1.3.0_biqbaboplfbrettd7655fr4n2y/node_modules/react-helmet-async/lib/index.module.js?v=e3bc4c16:
ReferenceError: require is not defined
    at /@fs/C:/Users/benno/Desktop/Workspace/Projects/_web/physicaldotart/node_modules/.pnpm/prop-types@15.8.1/node_modules/prop-types/index.js?v=e3bc4c16:7:0
    at instantiateModule (C:\Users\benno\Desktop\Workspace\Projects\_web\physicaldotart\node_modules\.pnpm\vite@2.9.14\node_modules\vite\dist\node\chunks\dep-c9998dc6.js:50311:15)
3:40:46 PM [vite] Error when evaluating SSR module /@fs/C:/Users/benno/Desktop/Workspace/Projects/_web/physicaldotart/node_modules/.pnpm/@shopify+hydrogen@1.0.2_jg75uhdbwv2u6vidkkv2ol6afi/node_modules/@shopify/hydrogen/dist/esnext/foundation/HydrogenRequest/HydrogenRequest.server.js:
ReferenceError: require is not defined
    at /@fs/C:/Users/benno/Desktop/Workspace/Projects/_web/physicaldotart/node_modules/.pnpm/prop-types@15.8.1/node_modules/prop-types/index.js?v=e3bc4c16:5:0
    at instantiateModule (C:\Users\benno\Desktop\Workspace\Projects\_web\physicaldotart\node_modules\.pnpm\vite@2.9.14\node_modules\vite\dist\node\chunks\dep-c9998dc6.js:50311:15)
3:40:46 PM [vite] Error when evaluating SSR module /@fs/C:/Users/benno/Desktop/Workspace/Projects/_web/physicaldotart/node_modules/.pnpm/@shopify+hydrogen@1.0.2_jg75uhdbwv2u6vidkkv2ol6afi/node_modules/@shopify/hydrogen/dist/esnext/entry-server.js?v=e3bc4c16:
ReferenceError: require is not defined
    at /@fs/C:/Users/benno/Desktop/Workspace/Projects/_web/physicaldotart/node_modules/.pnpm/prop-types@15.8.1/node_modules/prop-types/index.js?v=e3bc4c16:3:0
    at instantiateModule (C:\Users\benno\Desktop\Workspace\Projects\_web\physicaldotart\node_modules\.pnpm\vite@2.9.14\node_modules\vite\dist\node\chunks\dep-c9998dc6.js:50311:15)
3:40:46 PM [vite] Error when evaluating SSR module /src/App.server:
ReferenceError: require is not defined
    at /@fs/C:/Users/benno/Desktop/Workspace/Projects/_web/physicaldotart/node_modules/.pnpm/prop-types@15.8.1/node_modules/prop-types/index.js?v=e3bc4c16:1:0
    at instantiateModule (C:\Users\benno\Desktop\Workspace\Projects\_web\physicaldotart\node_modules\.pnpm\vite@2.9.14\node_modules\vite\dist\node\chunks\dep-c9998dc6.js:50311:15)
```

![image](https://user-images.githubusercontent.com/57860196/178147327-e4755d29-3f06-4cb6-99a9-b6941cc3d766.png)

**Comment by bennobuilder** [comment]
https://github.com/physical-art/physicaldotart/commit/4826367e37f63ef08f61c60e09565be943b2aabc
